### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by SavitskyiRoman** [OReshetnikov/new-project#1]
1) First column should be bold **- done;**
2) Footer should be fixed **- done;**
3) Placeholder should be white Firefox **- done;**
4) Old reset. hgroup deprecated
5)  background-image: url('data:image/png;'); **- done**
    background-size: 10%;
    background-repeat: no-repeat;
    background-position: 98% 0.3125em;
If you have 3 or more properties, please group it
6) http://prntscr.com/c41x2e Use tab or spaces but not mixed. Use space after : You shouldn't mix it **- done;**

PS:  onclick="swAdd()" Move this part to JS **- done.**
http://prntscr.com/c41y84
Good job!

**Comment by OReshetnikov** [comment]
All issues fixed. But I disagree with 4th comment. I used reset.css from Eric Meyer and this reset.css has v2.0 | 20110126, it's latest version on site.

**Comment by SavitskyiRoman** [comment]
Yes. I know about old module that didn't update. It will be better to get another forks or versions,
Because you will get a lot of problem. 

You can research and look on this discussing when you have a time
http://stackoverflow.com/questions/3485720/which-html5-reset-css-do-you-use-and-why
